# Generated by Django 2.2 on 2019-05-31 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField(blank=True, null=True)),
                ('bill_to', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('order_taken_by', models.TextField(blank=True, null=True)),
                ('date_ordered', models.TextField(blank=True, null=True)),
                ('date_promised', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_materials_and_labor', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('total_for_extras', models.TextField(blank=True, null=True)),
                ('grand_total', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid Sheet',
                'verbose_name_plural': 'Bid Sheets',
            },
        ),
    ]
