# Generated by Django 2.2 on 2019-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidsheet', '0002_auto_20190531_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsheet',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
